FROM node:22-alpine
WORKDIR /app

ENV NODE_ENV=development
COPY package.json package-lock.json ./
RUN npm ci

COPY . .

EXPOSE 5173

CMD ["npm", "run", "stage", "--", "--host", "0.0.0.0", "--port", "5173"]
